FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY Jcf.QuinzePontos.Domain/Jcf.QuinzePontos.Domain.csproj Jcf.QuinzePontos.Domain/
COPY Jcf.QuinzePontos.infrastructure/Jcf.QuinzePontos.Infrastructure.csproj Jcf.QuinzePontos.infrastructure/
COPY Jcf.QuinzePontos.Application/Jcf.QuinzePontos.Application.csproj Jcf.QuinzePontos.Application/
COPY Jcf.QuinzePontos.GetResultsWorker/Jcf.QuinzePontos.GetResultsWorker.csproj Jcf.QuinzePontos.GetResultsWorker/
RUN dotnet restore Jcf.QuinzePontos.GetResultsWorker/Jcf.QuinzePontos.GetResultsWorker.csproj

COPY . .
RUN dotnet publish Jcf.QuinzePontos.GetResultsWorker/Jcf.QuinzePontos.GetResultsWorker.csproj \
    -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Jcf.QuinzePontos.GetResultsWorker.dll"]
