// <auto-generated />
using System;
using Jcf.QuinzePontos.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jcf.QuinzePontos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260217204135_AlterAjustandoDataParaUtc")]
    partial class AlterAjustandoDataParaUtc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("loto_facil")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilConcurso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("Acumulado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataApuracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataProximoConcurso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LocalSorteio")
                        .HasColumnType("text");

                    b.Property<string>("NomeMunicipioUFSorteio")
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<bool?>("UltimoConcurso")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ValorAcumuladoConcursoEspecial")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ValorAcumuladoProximoConcurso")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ValorArrecadado")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ValorEstimadoProximoConcurso")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Concursos", "loto_facil");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilDezenas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long?>("LotofacilConcursoId")
                        .HasColumnType("bigint");

                    b.Property<int>("N1")
                        .HasColumnType("integer");

                    b.Property<int>("N10")
                        .HasColumnType("integer");

                    b.Property<int>("N11")
                        .HasColumnType("integer");

                    b.Property<int>("N12")
                        .HasColumnType("integer");

                    b.Property<int>("N13")
                        .HasColumnType("integer");

                    b.Property<int>("N14")
                        .HasColumnType("integer");

                    b.Property<int>("N15")
                        .HasColumnType("integer");

                    b.Property<int>("N2")
                        .HasColumnType("integer");

                    b.Property<int>("N3")
                        .HasColumnType("integer");

                    b.Property<int>("N4")
                        .HasColumnType("integer");

                    b.Property<int>("N5")
                        .HasColumnType("integer");

                    b.Property<int>("N6")
                        .HasColumnType("integer");

                    b.Property<int>("N7")
                        .HasColumnType("integer");

                    b.Property<int>("N8")
                        .HasColumnType("integer");

                    b.Property<int>("N9")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LotofacilConcursoId")
                        .IsUnique();

                    b.ToTable("Dezenas", "loto_facil");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilGanhadorUF", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Ganhadores")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long?>("LotofacilConcursoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Municipio")
                        .HasColumnType("text");

                    b.Property<string>("UF")
                        .HasColumnType("text");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LotofacilConcursoId");

                    b.ToTable("GanhadoresUF", "loto_facil");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilRateio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoFaixa")
                        .HasColumnType("text");

                    b.Property<int?>("Faixa")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long?>("LotofacilConcursoId")
                        .HasColumnType("bigint");

                    b.Property<int?>("NumeroDeGanhadores")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ValorPremio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("LotofacilConcursoId");

                    b.ToTable("Rateios", "loto_facil");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilDezenas", b =>
                {
                    b.HasOne("Jcf.QuinzePontos.Domain.Entities.LotofacilConcurso", "LotofacilConcurso")
                        .WithOne("Dezenas")
                        .HasForeignKey("Jcf.QuinzePontos.Domain.Entities.LotofacilDezenas", "LotofacilConcursoId");

                    b.Navigation("LotofacilConcurso");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilGanhadorUF", b =>
                {
                    b.HasOne("Jcf.QuinzePontos.Domain.Entities.LotofacilConcurso", "LotofacilConcurso")
                        .WithMany("GanhadoresUF")
                        .HasForeignKey("LotofacilConcursoId");

                    b.Navigation("LotofacilConcurso");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilRateio", b =>
                {
                    b.HasOne("Jcf.QuinzePontos.Domain.Entities.LotofacilConcurso", "LotofacilConcurso")
                        .WithMany("Rateios")
                        .HasForeignKey("LotofacilConcursoId");

                    b.Navigation("LotofacilConcurso");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilConcurso", b =>
                {
                    b.Navigation("Dezenas");

                    b.Navigation("GanhadoresUF");

                    b.Navigation("Rateios");
                });
#pragma warning restore 612, 618
        }
    }
}
