// <auto-generated />
using System;
using Jcf.QuinzePontos.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jcf.QuinzePontos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260124185728_InitialLotoFacilPart2")]
    partial class InitialLotoFacilPart2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("loto_facil")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilConcurso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Acumulado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataApuracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataProximoConcurso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LocalSorteio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeMunicipioUFSorteio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<bool>("UltimoConcurso")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorAcumuladoConcursoEspecial")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorAcumuladoProximoConcurso")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorArrecadado")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorEstimadoProximoConcurso")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Concursos", "loto_facil");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilDezena", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ConcursoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConcursoId");

                    b.ToTable("Dezenas", "loto_facil");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilGanhadorUF", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ConcursoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Ganhadores")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConcursoId");

                    b.ToTable("GanhadoresUF", "loto_facil");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilRateio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ConcursoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoFaixa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Faixa")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("NumeroDeGanhadores")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorPremio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ConcursoId");

                    b.ToTable("Rateios", "loto_facil");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilDezena", b =>
                {
                    b.HasOne("Jcf.QuinzePontos.Domain.Entities.LotofacilConcurso", "Concurso")
                        .WithMany("Dezenas")
                        .HasForeignKey("ConcursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concurso");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilGanhadorUF", b =>
                {
                    b.HasOne("Jcf.QuinzePontos.Domain.Entities.LotofacilConcurso", "Concurso")
                        .WithMany("GanhadoresUF")
                        .HasForeignKey("ConcursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concurso");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilRateio", b =>
                {
                    b.HasOne("Jcf.QuinzePontos.Domain.Entities.LotofacilConcurso", "Concurso")
                        .WithMany("Rateios")
                        .HasForeignKey("ConcursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concurso");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilConcurso", b =>
                {
                    b.Navigation("Dezenas");

                    b.Navigation("GanhadoresUF");

                    b.Navigation("Rateios");
                });
#pragma warning restore 612, 618
        }
    }
}
