// <auto-generated />
using System;
using Jcf.QuinzePontos.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jcf.QuinzePontos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703151749_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("loto_facil")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserCreatedId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("UserUpdateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserUpdateId");

                    b.ToTable("AspNetUsers", "loto_facil");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilConcurso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("Acumulado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataApuracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataProximoConcurso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LocalSorteio")
                        .HasColumnType("text");

                    b.Property<string>("NomeMunicipioUFSorteio")
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<bool?>("UltimoConcurso")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ValorAcumuladoConcursoEspecial")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ValorAcumuladoProximoConcurso")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ValorArrecadado")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ValorEstimadoProximoConcurso")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Concursos", "loto_facil");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilDezenas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long?>("LotofacilConcursoId")
                        .HasColumnType("bigint");

                    b.Property<int>("N1")
                        .HasColumnType("integer");

                    b.Property<int>("N10")
                        .HasColumnType("integer");

                    b.Property<int>("N11")
                        .HasColumnType("integer");

                    b.Property<int>("N12")
                        .HasColumnType("integer");

                    b.Property<int>("N13")
                        .HasColumnType("integer");

                    b.Property<int>("N14")
                        .HasColumnType("integer");

                    b.Property<int>("N15")
                        .HasColumnType("integer");

                    b.Property<int>("N2")
                        .HasColumnType("integer");

                    b.Property<int>("N3")
                        .HasColumnType("integer");

                    b.Property<int>("N4")
                        .HasColumnType("integer");

                    b.Property<int>("N5")
                        .HasColumnType("integer");

                    b.Property<int>("N6")
                        .HasColumnType("integer");

                    b.Property<int>("N7")
                        .HasColumnType("integer");

                    b.Property<int>("N8")
                        .HasColumnType("integer");

                    b.Property<int>("N9")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LotofacilConcursoId")
                        .IsUnique();

                    b.ToTable("Dezenas", "loto_facil");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilGanhadorUF", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Ganhadores")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long?>("LotofacilConcursoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Municipio")
                        .HasColumnType("text");

                    b.Property<string>("UF")
                        .HasColumnType("text");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LotofacilConcursoId");

                    b.ToTable("GanhadoresUF", "loto_facil");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilNumeroEstatistica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentAbsenceStreak")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<int>("FreqLast10")
                        .HasColumnType("integer");

                    b.Property<int>("FreqLast100")
                        .HasColumnType("integer");

                    b.Property<int>("FreqLast15")
                        .HasColumnType("integer");

                    b.Property<int>("FreqLast20")
                        .HasColumnType("integer");

                    b.Property<int>("FreqLast5")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long?>("LotofacilConcursoId")
                        .HasColumnType("bigint");

                    b.Property<int>("NumeroId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalAppearances")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LotofacilConcursoId");

                    b.ToTable("NumeroEstatisticas", "loto_facil");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilRateio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoFaixa")
                        .HasColumnType("text");

                    b.Property<int?>("Faixa")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long?>("LotofacilConcursoId")
                        .HasColumnType("bigint");

                    b.Property<int?>("NumeroDeGanhadores")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ValorPremio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("LotofacilConcursoId");

                    b.ToTable("Rateios", "loto_facil");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "loto_facil");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "loto_facil");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "loto_facil");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "loto_facil");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "loto_facil");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "loto_facil");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Jcf.QuinzePontos.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserCreatedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Jcf.QuinzePontos.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserUpdateId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilDezenas", b =>
                {
                    b.HasOne("Jcf.QuinzePontos.Domain.Entities.LotofacilConcurso", "LotofacilConcurso")
                        .WithOne("Dezenas")
                        .HasForeignKey("Jcf.QuinzePontos.Domain.Entities.LotofacilDezenas", "LotofacilConcursoId");

                    b.Navigation("LotofacilConcurso");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilGanhadorUF", b =>
                {
                    b.HasOne("Jcf.QuinzePontos.Domain.Entities.LotofacilConcurso", "LotofacilConcurso")
                        .WithMany("GanhadoresUF")
                        .HasForeignKey("LotofacilConcursoId");

                    b.Navigation("LotofacilConcurso");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilNumeroEstatistica", b =>
                {
                    b.HasOne("Jcf.QuinzePontos.Domain.Entities.LotofacilConcurso", "LotofacilConcurso")
                        .WithMany()
                        .HasForeignKey("LotofacilConcursoId");

                    b.Navigation("LotofacilConcurso");
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilRateio", b =>
                {
                    b.HasOne("Jcf.QuinzePontos.Domain.Entities.LotofacilConcurso", "LotofacilConcurso")
                        .WithMany("Rateios")
                        .HasForeignKey("LotofacilConcursoId");

                    b.Navigation("LotofacilConcurso");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Jcf.QuinzePontos.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Jcf.QuinzePontos.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jcf.QuinzePontos.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Jcf.QuinzePontos.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jcf.QuinzePontos.Domain.Entities.LotofacilConcurso", b =>
                {
                    b.Navigation("Dezenas");

                    b.Navigation("GanhadoresUF");

                    b.Navigation("Rateios");
                });
#pragma warning restore 612, 618
        }
    }
}
