<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Jcf.QuinzePontos.GetResultsWorker-10518b98-4c84-4502-9d06-e7f4dcda348e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jcf.QuinzePontos.Application\Jcf.QuinzePontos.Application.csproj" />
    <ProjectReference Include="..\Jcf.QuinzePontos.infrastructure\Jcf.QuinzePontos.Infrastructure.csproj" />
  </ItemGroup>
</Project>
